import React, { useState, useRef } from 'react';
import { useNavigate } from 'react-router-dom';
import { useApp } from '../../context/AppContext';
import { parseJSONL, normalizeRecord } from '../../context/AppContext';
import Navbar from '../../components/Navbar';

function validateRecords(records, type) {
  const errors = [];
  const ids = new Set();
  records.forEach((r, i) => {
    const lbl = `Record #${i + 1}`;
    if (ids.has(r.id)) errors.push(`${lbl}: duplicate id ${r.id}`);
    ids.add(r.id);

    if (type === 'ner') {
       if (!r.text) errors.push(`${lbl}: missing 'text' field for NER sentence`);
    } else {
       if (!r.english)  errors.push(`${lbl}: missing English sentence`);
       if (!r.target)   errors.push(`${lbl}: missing target (Malayalam/Hindi) sentence`);
       if (!Array.isArray(r.alignment) || r.alignment.length === 0)
         errors.push(`${lbl}: alignment array is empty or missing`);
    }
  });
  return errors;
}

export default function UploadPage() {
  const { state, actions } = useApp();
  const navigate    = useNavigate();
  const fileRef     = useRef(null);

  const [dragging,  setDragging]  = useState(false);
  const [fileName,  setFileName]  = useState('');
  const [errors,    setErrors]    = useState([]);
  const [warnings,  setWarnings]  = useState([]);
  const [preview,   setPreview]   = useState(null);
  const [parsed,    setParsed]    = useState(null);
  const [loading,   setLoading]   = useState(false);

  const processFile = async (file) => {
    if (!file) return;
    setLoading(true); setErrors([]); setWarnings([]); setPreview(null); setParsed(null);
    setFileName(file.name);
    try {
      const text = await file.text();
      let rawRecords = [];

      const trimmed = text.trim();
      if (trimmed.startsWith('['))      rawRecords = JSON.parse(trimmed);
      else if (trimmed.startsWith('{')) rawRecords = parseJSONL(trimmed);
      else                               rawRecords = parseJSONL(trimmed);  // .txt JSONL

      if (!rawRecords.length) throw new Error('File contains no records.');
      
      let normalized;
      let warn = [];
      
      if (state.projectType === 'ner') {
         normalized = rawRecords.map((r, i) => {
            const nr = { ...r, id: r.id ?? i + 1, text: r.text ?? r.sentence ?? '' };
            nr.tokens = nr.tokens ?? nr.text.trim().split(/\s+/).filter(Boolean);
            return nr;
         });
      } else {
         normalized = rawRecords.map((r, i) => normalizeRecord(r, i));
         if (!rawRecords[0].english_tokens && !rawRecords[0].target_tokens)
            warn.push('Tokens were auto-generated by splitting on whitespace. Verify for complex text.');
      }

      const errs = validateRecords(normalized, state.projectType);
      if (errs.length) { setErrors(errs); setLoading(false); return; }

      setWarnings(warn);
      setParsed(normalized);
      setPreview(normalized.slice(0, 2));
    } catch (e) {
      setErrors([`Parse error: ${e.message}`]);
    } finally { setLoading(false); }
  };

  const onDrop  = (e) => { e.preventDefault(); setDragging(false); processFile(e.dataTransfer.files[0]); };
  const onChange = (e) => processFile(e.target.files[0]);

  const handleContinue = () => {
    if (!parsed) return;
    actions.setUploadedData(parsed);
    navigate('/user/purpose');
  };

  return (
    <div style={{ minHeight: '100vh', background: '#f1f5f9' }}>
      <Navbar showBack backTo="/user/instructions" backLabel="Instructions" />
      <div className="page-container">
        <div className="step-indicator">
          <div className="step completed"><div className="step-num">✓</div>Project Type</div>
          <div className="step-line completed"></div>
          <div className="step completed"><div className="step-num">✓</div>Instructions</div>
          <div className="step-line completed"></div>
          <div className="step active"><div className="step-num">3</div>Upload</div>
          <div className="step-line"></div>
          <div className="step"><div className="step-num">4</div>Purpose</div>
          <div className="step-line"></div>
          <div className="step"><div className="step-num">5</div>Configure</div>
        </div>
        <div className="card">
          <div className="card-header" style={{ background: '#ede9fe' }}>
            <span>📤</span> Upload Dataset
            <span className="badge badge-primary" style={{ marginLeft: 'auto' }}>Step 3 of 5</span>
          </div>
          <div className="card-body">
            {/* Drop zone */}
            <div
              onClick={() => fileRef.current?.click()}
              onDragOver={e => { e.preventDefault(); setDragging(true); }}
              onDragLeave={() => setDragging(false)}
              onDrop={onDrop}
              style={{
                border: `2px dashed ${dragging ? '#4f46e5' : parsed ? '#10b981' : '#cbd5e1'}`,
                borderRadius: 12, padding: '36px 20px', textAlign: 'center', cursor: 'pointer',
                background: dragging ? '#ede9fe' : parsed ? '#f0fdf4' : '#f8fafc',
                transition: 'all 0.2s', marginBottom: 18,
              }}
            >
              <div style={{ fontSize: 44, marginBottom: 10 }}>{loading ? '⏳' : parsed ? '✅' : '📂'}</div>
              <p style={{ fontWeight: 600, fontSize: '0.97rem', marginBottom: 5 }}>
                {loading ? 'Processing…' : parsed ? `✓ ${fileName} (${parsed.length} sentences)` : 'Drop .json / .jsonl / .txt here'}
              </p>
              <p style={{ fontSize: '0.82rem', color: '#64748b' }}>{parsed ? 'Click to replace' : 'or click to browse'}</p>
              <input ref={fileRef} type="file" accept=".json,.jsonl,.txt" style={{ display: 'none' }} onChange={onChange} />
            </div>

            {errors.length > 0 && (
              <div className="alert alert-error" style={{ flexDirection: 'column', alignItems: 'flex-start' }}>
                <strong>❌ {errors.length} validation error(s)</strong>
                <ul style={{ paddingLeft: 16, marginTop: 6 }}>
                  {errors.slice(0, 6).map((e, i) => <li key={i} style={{ fontSize: '0.83rem' }}>{e}</li>)}
                  {errors.length > 6 && <li style={{ fontSize: '0.83rem' }}>…and {errors.length - 6} more</li>}
                </ul>
              </div>
            )}
            {warnings.map((w, i) => <div key={i} className="alert alert-warning">⚠️ {w}</div>)}

            {/* Preview */}
            {preview && (
              <div style={{ marginTop: 20 }}>
                <h3 style={{ fontWeight: 700, fontSize: '0.93rem', marginBottom: 12 }}>
                  👁️ Preview <span className="badge badge-success">{parsed.length} total</span>
                </h3>
                {preview.map((rec, i) => (
                  <div key={i} style={{ border: '1px solid #e2e8f0', borderRadius: 10, padding: '14px 16px', background: '#fafafa', marginBottom: 12 }}>
                    <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 8 }}>
                      <span className="badge badge-info">ID {rec.id}</span>
                      <span style={{ fontSize: '0.78rem', color: '#64748b' }}>
                        {state.projectType === 'ner' ? `${rec.tokens.length} tokens` : `${rec.english_tokens.length} EN tokens · ${rec.target_tokens.length} ML tokens · ${rec.alignment.length} pairs`}
                      </span>
                    </div>
                    {state.projectType === 'ner' ? (
                      <div>
                        <span style={{ fontSize: '0.72rem', fontWeight: 700, color: '#0891b2', textTransform: 'uppercase', letterSpacing: '0.06em' }}>Dataset Sentence</span>
                        <p className={state.language === 'hindi' ? 'hi' : state.language === 'marathi' ? 'mr' : state.language === 'bengali' ? 'bn' : 'ml'} style={{ fontSize: '1rem', marginTop: 4 }}>{rec.text}</p>
                      </div>
                    ) : (
                      <>
                        <div style={{ marginBottom: 8 }}>
                          <span style={{ fontSize: '0.72rem', fontWeight: 700, color: '#4f46e5', textTransform: 'uppercase', letterSpacing: '0.06em' }}>English</span>
                          <p style={{ fontSize: '0.88rem', marginTop: 2 }}>{rec.english}</p>
                        </div>
                        <div style={{ marginBottom: 8 }}>
                          <span style={{ fontSize: '0.72rem', fontWeight: 700, color: '#059669', textTransform: 'uppercase', letterSpacing: '0.06em' }}>{state.language || 'Malayalam'} / Target</span>
                          <p className={state.language === 'hindi' ? 'hi' : state.language === 'marathi' ? 'mr' : state.language === 'bengali' ? 'bn' : 'ml'} style={{ fontSize: '0.93rem', marginTop: 2 }}>{rec.target}</p>
                        </div>
                        <div>
                          <span style={{ fontSize: '0.72rem', fontWeight: 700, color: '#92400e', textTransform: 'uppercase', letterSpacing: '0.06em' }}>Alignment Pairs ({rec.alignment.length})</span>
                          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 6, marginTop: 6 }}>
                            {rec.alignment.slice(0, 8).map((p, pi) => (
                              <span key={pi} style={{ background: '#fef9c3', border: '1px solid #fde68a', borderRadius: 6, padding: '2px 8px', fontSize: '0.8rem' }}>
                                {p.en_word} ↔ <span className={state.language === 'hindi' ? 'hi' : state.language === 'marathi' ? 'mr' : state.language === 'bengali' ? 'bn' : 'ml'}>{p.ml_word}</span>
                              </span>
                            ))}
                            {rec.alignment.length > 8 && <span style={{ fontSize: '0.8rem', color: '#94a3b8' }}>+{rec.alignment.length - 8} more</span>}
                          </div>
                        </div>
                      </>
                    )}
                  </div>
                ))}
              </div>
            )}

            <div style={{ display: 'flex', justifyContent: 'flex-end', gap: 10, marginTop: 24 }}>
              <button className="btn btn-secondary" onClick={() => navigate('/user/instructions')}>← Back</button>
              <button className="btn btn-primary btn-lg" onClick={handleContinue} disabled={!parsed || errors.length > 0}>
                Continue to Purpose →
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
